add context to syntax errors
fixes https://github.com/edgedb/edgedb-go/issues/116

A query snip-it with arrow and hint is introduced for syntax errors.

Example:
SELECT (foo (((1 2) 3)) 4)

produces

edgedb.EdgeQLSyntaxError: Unexpected token: <Token ICONST "2">
query:1:18

SELECT (foo (((1 2) 3)) 4)
                 ^ It appears that a ',' is missing in a tuple before '2'